-- DROP TABLE pi4dhl;
--
-- CREATE SEQUENCE SEQ_NAME AS INTEGER START WITH 100;

CREATE TABLE pi4dhl
(
--     id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
    id               INTEGER NOT NULL DEFAULT nextval('SEQ_NAME') ,
--     id               BIGSERIAL PRIMARY KEY ,
    date             TIMESTAMP DEFAULT now() NOT NULL,
    temperature      FLOAT                   NOT NULL,
    humidity         FLOAT                   NOT NULL
);